DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS users (
  user_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  email varchar(40) NOT NULL,
  login varchar(40) NOT NULL,
  name varchar(40) NOT NULL,
  birthday date
);

CREATE TABLE IF NOT EXISTS films (
  film_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name varchar NOT NULL,
  description varchar(200),
  release_date date,
  duration integer,
  mpa_id integer
);

CREATE TABLE IF NOT EXISTS film_likes (
  user_id integer,
  film_id integer
);

ALTER TABLE film_likes ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE film_likes ADD FOREIGN KEY (film_id) REFERENCES films (film_id);

CREATE TABLE IF NOT EXISTS friends (
  user_id integer,
  friend_id integer
);

ALTER TABLE friends ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE friends ADD FOREIGN KEY (friend_id) REFERENCES users (user_id);

CREATE TABLE IF NOT EXISTS mpa (
  mpa_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name varchar(30) NOT NULL
);
ALTER TABLE films ADD FOREIGN KEY (mpa_id) REFERENCES mpa (mpa_id);

CREATE TABLE IF NOT EXISTS genre (
  genre_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id integer,
  genre_id integer
);

ALTER TABLE film_genres ADD FOREIGN KEY (film_id) REFERENCES films (film_id);

ALTER TABLE film_genres ADD FOREIGN KEY (genre_id) REFERENCES genre (genre_id);

